### ISSUE TITLE
Using "input" vs. "data"

### ISSUE THREAD

**Issue by newyork-anthonyng** [marko-js-samples/marko-todomvc#2]
I saw this [code snippet](https://github.com/marko-js-samples/marko-todomvc/blob/master/components/todomvc-main/index.marko#L29) which used `data`. 

I couldn't find any documentation of what `data` was in the `4.0` docs. But I saw in the `3.0` docs that it worked similar to `input`.

Can `input` and `data` be used interchangeably?
Should we only use `input` in `4.0`? Or should we update the `4.0` docs to make mentions of `data`?

**Comment by austinkelleher** [comment]
@newyork-anthonyng `data` was renamed to `input` in Marko v4. We never actually added a deprecation warning, but it is deprecated. They can be used interchangeably. Would you be interested in opening a PR to fix this? Thanks!
